package cn.wangsr.mapper;

import cn.wangsr.dto.ShoppingGoods;

public interface ShoppingGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-goods
     *
     * @mbg.generated
     */
    int insert(ShoppingGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-goods
     *
     * @mbg.generated
     */
    int insertSelective(ShoppingGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-goods
     *
     * @mbg.generated
     */
    ShoppingGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShoppingGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShoppingGoods record);
}