package cn.wangsr.mapper;

import cn.wangsr.dto.ShoppingMyInfo;
import cn.wangsr.dto.ShoppingMyInfoKey;

public interface ShoppingMyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-myinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(ShoppingMyInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-myinfo
     *
     * @mbg.generated
     */
    int insert(ShoppingMyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-myinfo
     *
     * @mbg.generated
     */
    int insertSelective(ShoppingMyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-myinfo
     *
     * @mbg.generated
     */
    ShoppingMyInfo selectByPrimaryKey(ShoppingMyInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-myinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShoppingMyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-myinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShoppingMyInfo record);
}