package cn.wangsr.mapper;

import cn.wangsr.dto.ShoppingItems;

public interface ShoppingItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-items
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-items
     *
     * @mbg.generated
     */
    int insert(ShoppingItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-items
     *
     * @mbg.generated
     */
    int insertSelective(ShoppingItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-items
     *
     * @mbg.generated
     */
    ShoppingItems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-items
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShoppingItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-items
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShoppingItems record);
}