package cn.wangsr.mapper;

import cn.wangsr.dto.ShoppingOrderInfo;

public interface ShoppingOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-orderinfo
     *
     * @mbg.generated
     */
    int insert(ShoppingOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping-all-orderinfo
     *
     * @mbg.generated
     */
    int insertSelective(ShoppingOrderInfo record);
}