package cn.wangsr.dto;

import java.math.BigDecimal;

public class ShoppingGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-goods.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-goods.goodsName
     *
     * @mbg.generated
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-goods.goodsImage
     *
     * @mbg.generated
     */
    private String goodsimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-goods.goodsPrice
     *
     * @mbg.generated
     */
    private BigDecimal goodsprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-goods.goods-items-id
     *
     * @mbg.generated
     */
    private Integer goodsItemsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-goods.goodsDescription
     *
     * @mbg.generated
     */
    private String goodsdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-goods.goodsTags
     *
     * @mbg.generated
     */
    private String goodstags;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-goods.id
     *
     * @return the value of shopping-all-goods.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-goods.id
     *
     * @param id the value for shopping-all-goods.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-goods.goodsName
     *
     * @return the value of shopping-all-goods.goodsName
     *
     * @mbg.generated
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-goods.goodsName
     *
     * @param goodsname the value for shopping-all-goods.goodsName
     *
     * @mbg.generated
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-goods.goodsImage
     *
     * @return the value of shopping-all-goods.goodsImage
     *
     * @mbg.generated
     */
    public String getGoodsimage() {
        return goodsimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-goods.goodsImage
     *
     * @param goodsimage the value for shopping-all-goods.goodsImage
     *
     * @mbg.generated
     */
    public void setGoodsimage(String goodsimage) {
        this.goodsimage = goodsimage == null ? null : goodsimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-goods.goodsPrice
     *
     * @return the value of shopping-all-goods.goodsPrice
     *
     * @mbg.generated
     */
    public BigDecimal getGoodsprice() {
        return goodsprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-goods.goodsPrice
     *
     * @param goodsprice the value for shopping-all-goods.goodsPrice
     *
     * @mbg.generated
     */
    public void setGoodsprice(BigDecimal goodsprice) {
        this.goodsprice = goodsprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-goods.goods-items-id
     *
     * @return the value of shopping-all-goods.goods-items-id
     *
     * @mbg.generated
     */
    public Integer getGoodsItemsId() {
        return goodsItemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-goods.goods-items-id
     *
     * @param goodsItemsId the value for shopping-all-goods.goods-items-id
     *
     * @mbg.generated
     */
    public void setGoodsItemsId(Integer goodsItemsId) {
        this.goodsItemsId = goodsItemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-goods.goodsDescription
     *
     * @return the value of shopping-all-goods.goodsDescription
     *
     * @mbg.generated
     */
    public String getGoodsdescription() {
        return goodsdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-goods.goodsDescription
     *
     * @param goodsdescription the value for shopping-all-goods.goodsDescription
     *
     * @mbg.generated
     */
    public void setGoodsdescription(String goodsdescription) {
        this.goodsdescription = goodsdescription == null ? null : goodsdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-goods.goodsTags
     *
     * @return the value of shopping-all-goods.goodsTags
     *
     * @mbg.generated
     */
    public String getGoodstags() {
        return goodstags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-goods.goodsTags
     *
     * @param goodstags the value for shopping-all-goods.goodsTags
     *
     * @mbg.generated
     */
    public void setGoodstags(String goodstags) {
        this.goodstags = goodstags == null ? null : goodstags.trim();
    }
}