package cn.wangsr.dto;

public class ShoppingMyInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-myinfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-myinfo.openId
     *
     * @mbg.generated
     */
    private String openid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-myinfo.id
     *
     * @return the value of shopping-all-myinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-myinfo.id
     *
     * @param id the value for shopping-all-myinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-myinfo.openId
     *
     * @return the value of shopping-all-myinfo.openId
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-myinfo.openId
     *
     * @param openid the value for shopping-all-myinfo.openId
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }
}