package cn.wangsr.dto;

import java.math.BigDecimal;

public class ShoppingMyInfo extends ShoppingMyInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-myinfo.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-myinfo.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-myinfo.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-myinfo.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-myinfo.account
     *
     * @mbg.generated
     */
    private BigDecimal account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-myinfo.redPackets
     *
     * @mbg.generated
     */
    private BigDecimal redpackets;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-myinfo.receiptAddress
     *
     * @mbg.generated
     */
    private String receiptaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-myinfo.gender
     *
     * @mbg.generated
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-myinfo.avatarUrl
     *
     * @mbg.generated
     */
    private String avatarurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-myinfo.nickname
     *
     * @return the value of shopping-all-myinfo.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-myinfo.nickname
     *
     * @param nickname the value for shopping-all-myinfo.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-myinfo.country
     *
     * @return the value of shopping-all-myinfo.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-myinfo.country
     *
     * @param country the value for shopping-all-myinfo.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-myinfo.province
     *
     * @return the value of shopping-all-myinfo.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-myinfo.province
     *
     * @param province the value for shopping-all-myinfo.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-myinfo.city
     *
     * @return the value of shopping-all-myinfo.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-myinfo.city
     *
     * @param city the value for shopping-all-myinfo.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-myinfo.account
     *
     * @return the value of shopping-all-myinfo.account
     *
     * @mbg.generated
     */
    public BigDecimal getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-myinfo.account
     *
     * @param account the value for shopping-all-myinfo.account
     *
     * @mbg.generated
     */
    public void setAccount(BigDecimal account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-myinfo.redPackets
     *
     * @return the value of shopping-all-myinfo.redPackets
     *
     * @mbg.generated
     */
    public BigDecimal getRedpackets() {
        return redpackets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-myinfo.redPackets
     *
     * @param redpackets the value for shopping-all-myinfo.redPackets
     *
     * @mbg.generated
     */
    public void setRedpackets(BigDecimal redpackets) {
        this.redpackets = redpackets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-myinfo.receiptAddress
     *
     * @return the value of shopping-all-myinfo.receiptAddress
     *
     * @mbg.generated
     */
    public String getReceiptaddress() {
        return receiptaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-myinfo.receiptAddress
     *
     * @param receiptaddress the value for shopping-all-myinfo.receiptAddress
     *
     * @mbg.generated
     */
    public void setReceiptaddress(String receiptaddress) {
        this.receiptaddress = receiptaddress == null ? null : receiptaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-myinfo.gender
     *
     * @return the value of shopping-all-myinfo.gender
     *
     * @mbg.generated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-myinfo.gender
     *
     * @param gender the value for shopping-all-myinfo.gender
     *
     * @mbg.generated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-myinfo.avatarUrl
     *
     * @return the value of shopping-all-myinfo.avatarUrl
     *
     * @mbg.generated
     */
    public String getAvatarurl() {
        return avatarurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-myinfo.avatarUrl
     *
     * @param avatarurl the value for shopping-all-myinfo.avatarUrl
     *
     * @mbg.generated
     */
    public void setAvatarurl(String avatarurl) {
        this.avatarurl = avatarurl == null ? null : avatarurl.trim();
    }
}