package cn.wangsr.dto;

import java.util.Date;

public class ShoppingOrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-orderinfo.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-orderinfo.orderTime
     *
     * @mbg.generated
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-orderinfo.orderStatus
     *
     * @mbg.generated
     */
    private Byte orderstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-orderinfo.personalOpenId
     *
     * @mbg.generated
     */
    private String personalopenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-orderinfo.orderDetail
     *
     * @mbg.generated
     */
    private String orderdetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-orderinfo.id
     *
     * @return the value of shopping-all-orderinfo.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-orderinfo.id
     *
     * @param id the value for shopping-all-orderinfo.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-orderinfo.orderTime
     *
     * @return the value of shopping-all-orderinfo.orderTime
     *
     * @mbg.generated
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-orderinfo.orderTime
     *
     * @param ordertime the value for shopping-all-orderinfo.orderTime
     *
     * @mbg.generated
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-orderinfo.orderStatus
     *
     * @return the value of shopping-all-orderinfo.orderStatus
     *
     * @mbg.generated
     */
    public Byte getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-orderinfo.orderStatus
     *
     * @param orderstatus the value for shopping-all-orderinfo.orderStatus
     *
     * @mbg.generated
     */
    public void setOrderstatus(Byte orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-orderinfo.personalOpenId
     *
     * @return the value of shopping-all-orderinfo.personalOpenId
     *
     * @mbg.generated
     */
    public String getPersonalopenid() {
        return personalopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-orderinfo.personalOpenId
     *
     * @param personalopenid the value for shopping-all-orderinfo.personalOpenId
     *
     * @mbg.generated
     */
    public void setPersonalopenid(String personalopenid) {
        this.personalopenid = personalopenid == null ? null : personalopenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-orderinfo.orderDetail
     *
     * @return the value of shopping-all-orderinfo.orderDetail
     *
     * @mbg.generated
     */
    public String getOrderdetail() {
        return orderdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-orderinfo.orderDetail
     *
     * @param orderdetail the value for shopping-all-orderinfo.orderDetail
     *
     * @mbg.generated
     */
    public void setOrderdetail(String orderdetail) {
        this.orderdetail = orderdetail == null ? null : orderdetail.trim();
    }
}