package cn.wangsr.dto;

public class ShoppingItems {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-items.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping-all-items.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-items.id
     *
     * @return the value of shopping-all-items.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-items.id
     *
     * @param id the value for shopping-all-items.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping-all-items.name
     *
     * @return the value of shopping-all-items.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping-all-items.name
     *
     * @param name the value for shopping-all-items.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}